In [73]:
# https://www.kaggle.com/code/rhodiumbeng/classifying-multi-label-comments-0-9741-lb

In [74]:
import warnings
warnings.simplefilter("ignore")

In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [76]:
!pip install emoji

Requirement already satisfied: emoji in c:\users\peerapat\anaconda3\lib\site-packages (2.10.1)

DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

In [77]:
import string
import emoji

In [78]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# 1. Load data

In [79]:
df = pd.read_csv('prachathai-67k.csv')

In [80]:
df.head(5)

,url,date,title,body_text,labels
0,https://prachatai.com/print/42,2004-08-24 14:31,"นักวิจัยหนุน ""แม้ว"" เปิด ""จีเอ็มโอ""",ประชาไท --- 23 ส.ค.2547 นักวิจัยฯ ชี้นโยบายจี...,"['ข่าว', 'สิ่งแวดล้อม']"
1,https://prachatai.com/print/41,2004-08-24 14:22,ภาคประชาชนต้านเปิดเสรีจีเอ็มโอ,ประชาไท- 23 ส.ค.2547 นักวิชาการ ภาคประชาชน จ...,"['ข่าว', 'สิ่งแวดล้อม']"
2,https://prachatai.com/print/43,2004-08-24 15:17,จุฬาฯ ห่วงจีเอ็มโอลามข้าวไทย,นโยบายที่อนุญาตให้ปลูกร่วมกับพืชอื่นได้นั้นถื...,"['ข่าว', 'สิ่งแวดล้อม']"
3,https://prachatai.com/print/45,2004-08-24 15:58,ฟองสบู่การเมืองแตก ทักษิณหมดกึ๋น ชนชั้นกลางหมด...,ประชาไท -- 23 ส.ค. 47 ขาประจำทักษิณ ฟันธง ฟอง...,"['ข่าว', 'การเมือง', 'คณะเศรษฐศาสตร์ มหาวิทยาล..."
4,https://prachatai.com/print/47,2004-08-24 16:10,กอต.เสนอเลิกถนนคลองลาน-อุ้มผาง,ประชาไท-23 ส.ค.47 คณะกรรมการอนุรักษ์ ผืนป่าตะ...,"['ข่าว', 'สิ่งแวดล้อม']"

In [81]:
df.shape

(67889, 5)

# 2. Check data quality

data type

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67889 entries, 0 to 67888
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   url        67889 non-null  object
 1   date       67889 non-null  object
 2   title      67889 non-null  object
 3   body_text  67889 non-null  object
 4   labels     67889 non-null  object
dtypes: object(5)
memory usage: 2.6+ MB

unique value

In [83]:
for i in df.columns:
    print('Columns name: ', i)
    print('Unique value: ', df[i].unique())
    print('Count unique value: ', df[i].nunique())
    print('-'*10)

Columns name:  url
Unique value:  ['https://prachatai.com/print/42' 'https://prachatai.com/print/41'
 'https://prachatai.com/print/43' ... 'https://prachatai.com/print/79625'
 'https://prachatai.com/print/79628' 'https://prachatai.com/print/79629']
Count unique value:  67889
----------
Columns name:  date
Unique value:  ['2004-08-24 14:31' '2004-08-24 14:22' '2004-08-24 15:17' ...
 '2018-11-15 12:47' '2018-11-15 20:45' '2018-11-15 21:34']
Count unique value:  66732
----------
Columns name:  title
Unique value:  ['นักวิจัยหนุน  "แม้ว"  เปิด  "จีเอ็มโอ"' 'ภาคประชาชนต้านเปิดเสรีจีเอ็มโอ'
 'จุฬาฯ ห่วงจีเอ็มโอลามข้าวไทย' ...
 'ยุติวงจรผลัดกันเกาหลัง ด้วยการยื่นบัญชีทรัพย์สินฯ'
 'รัฐสวัสดิการ 101 กับ\xa0ภาคภูมิ แสงกนกกุล :\xa0การจัดวางความสัมพันธ์ใหม่ระหว่างรัฐ-สังคม'
 "ชาวอุยกูร์ในสหรัฐฯ ชุมนุมวันประกาศเอกราช เรียกร้องกดดันจีนกรณี 'ค่ายกักกัน'"]
Count unique value:  67417
----------
Columns name:  body_text
Unique value:  ['ประชาไท --- 23 ส.ค.2547  นักวิจัยฯ ชี้นโยบายจีเอ็มโอเอื้อต่อการค้นคว้าวิจัย แต่ไม่ใช่คำตอบทั้งหมด ขณะที่ผอ.สวทช.ระบุมาตรการตรวจสอบความปลอดภัยมีมาก่อนการกำหนดนโยบายของรัฐบาล เพียงแต่ทบทวนและปรับปรุงเพิ่มเติม  \nสำนักงานพัฒนาวิทยาศาสตร์และเทคโนโลยี  จัดสัมมนาเกี่ยวกับมะละกอดัดแปลงพันธุกรรมในประเทศไทย มีนักวิชาการ นักวิจัยจากกรมวิชาการเกษตร  มหาวิทยาลัยเกษตรศาสตร์  และมหาวิทยาลัยมหิดลเข้าร่วม  โดยมีการนำเสนอผลการศึกษาทดลองที่ผ่านมา  ซึ่งพบว่ามะละกอ\nจีเอ็มโอผ่านการทดสอบความปลอดภัยทางชีวภาพสิ่งแวดล้อมและอาหารระดับหนึ่งเท่านั้น    \n "การค้นคว้าวิจัยมะละกอจีเอ็มโอรวมถึงพืชชนิดอื่นๆ ต้องทำทั้งในโรงเรือนปิด แปลงทดลอง รวมทั้งในระดับไร่นา  แต่ที่ผ่านมาทำได้แค่สองระดับ  ซึ่งถือว่า ถูกต้องแล้วที่มีนโยบายใหม่นี้ออกมาเป็นการเปิดโอกาสให้ทำการทดลองในระดับไร่นา "ผศ.พิสสวรรณ เจียมสมบัติ จากหน่วยปฏิบัติการพันธุวิศวกรรมด้านพืช มหาวิทยาลัยเกษตรศาสตร์กล่าว    \nน.ส.สุณี เกิดบัณฑิต นักวิชาการจากสถาบันอณูชีววิทยาและพันธุศาสตร์  มหาวิทยาลัยมหิดลกล่าวว่า การพัฒนาเทคโนโลยีการตัดต่อพันธุกรรมนี้มีประโยชน์ในหลายด้าน  แต่ก็ไม่ใช่ออลอินวัน  เพราะเมื่อออกมาแล้วอาจจะต้านทานไวรัสได้ตัวหนึ่ง  แต่ก็ไม่สามารถต้านทานไวรัสสายพันธุ์อื่นๆได้  นอกจากนั้นต้องใช้งบประมาณมหาศาล  และใช้ระยะเวลาในการศึกษาวิจัยค่อนข้างยาวนาน   \nรศ.ศักรินทร์ ภูมิรัตน ผู้อำนวยการสำนักงานพัฒนาวิทยาศาสตร์และเทคโนโลยีแห่งประเทศไทย (สวทช.) กล่าวว่า  นโยบายของรัฐที่ออกมาเท่ากับเป็นการยอมรับให้มีการพัฒนาจีเอ็มโอในประเทศไทย  โดยมีการประเมินผลความปลอดภัยที่รัดกุม  ซึ่งมาตรการดังกล่าวมีมาก่อนที่รัฐบาลจะกำหนดนโยบายใหม่นี้  เพียงแต่เมื่อกำหนดนโยบายออกมาชัดเจนก็ต้องมีการกลับไปทบทวนและปรับปรุงเพิ่มเติม  โดยเสนอกรอบเวลาไว้ 3 เดือนซึ่งคิดว่าเพียงพอ     \nนายรุจ  วัลยะเสวี  ประธานคณะทำงานเพื่อประเมินความปลอดภัยทางชีวภาพของมะละกอดัดแปลงพันธุกรรมกล่าวว่า  ขณะนี้คณะทำงานฯกำลังติดตามการทดสอบความทนทานของมะละกอต่อโรคใบด่างวงแหวนซึ่งเป็นโรคระบาดที่สร้างความเสียหายหนักหน่วงอยู่  โดยคณะทำงานเพื่อประเมินความปลอดภัยนี้จะแบ่งเป็นหลายชุดแยกไปตามชนิดของพืช  มีผู้เชี่ยวชาญสาขาต่างๆ มาช่วยพิจารณา  ถือเป็นที่ปรึกษาด้าน วิทยาศาสตร์ขององค์การอาหารและยา (อย.) ก่อนที่อย.จะพิจารณาด้านอื่นๆ ต่อไป     \nทั้งนี้ในสิ้นเดือนนี้จะมีการจัดทำประชาพิจารณ์ในแนวทางปฏิบัติที่คณะทำงานฯ จะนำเสนอต่อ อย. เพื่อเป็นมาตรฐานในการพิจารณาความปลอดภัยด้านอาหารต่อไป   \n  รายงานโดย : มุทิตา เชื้อชั่ง\nศูนย์ข่าวประชาไท  \n'
 'ประชาไท- 23 ส.ค.2547   นักวิชาการ ภาคประชาชน จับมือต้านนโยบายรัฐเปิดเสรีจีเอ็มโอ หวั่นไทยเสียค่าโง่ต่างชาติ  เตรียมชุมนุมคัดค้านหน้าทำเนียบฯ พรุ่งนี้  \nกลุ่มองค์กรผู้บริโภค เครือข่ายภาคเกษตรกรรม นักวิชาการ และกลุ่มศึกษาเขตการค้าเสรีภาคประชาชน (FTA WATCH) แสดงจุดยืนคัดค้านมติปลูกพืชจีเอ็มโออย่างเสรี เพราะเกรงว่าจะเป็นอันตรายต่อผู้บริโภคและสิ่งแวดล้อม    \n  "อยากให้รัฐบาลทบทวนมติดังกล่าว มิเช่นนั้นกลุ่มผู้ค้านเปิดเสรีจีเอ็มโอทั้งหมดจะเคลื่อนไหวใหญ่  "นายวิฑูรย์ เลี่ยนจำรูญ ผู้อำนวยการไบโอไทยระบุ    \nพรุ่งนี้เวลา 9.00 น. กลุ่มผู้คัดค้านการปลูกและนำเข้าพืชจีเอ็มโอ จะรวมตัวกันที่หน้าทำเนียบรัฐบาลเพื่อเรียกร้องให้ พ.ต.ท.ทักษิณ ชินวัตร นายกรัฐมนตรีทบทวนมติดังกล่าว   \nนายสุรวิช วรรณไกรโรจน์ อาจารย์คณะเกษตรศาสตร์  มหาวิทยาลัยเกษตรศาสตร์ กล่าวว่า รู้สึกเป็นห่วงเรื่องนี้มาก เพราะขณะนี้ไทยยังไม่มีกฎหมายกำกับดูแลการใช้ประโยชน์จากจีเอ็มโอ ประกอบกับยังไม่มีนักวิทยาศาสตร์คนไหนกล้ายืนยันว่าจีเอ็มโอปลอดภัยทั้งคน สัตว์ พืช และสิ่งแวดล้อม    \n " ผมเป็นห่วงกลัวว่าเกษตรกรจะเดือดร้อน เพราะรัฐบาลเร่งรัดเปิดเสรีจีเอ็มโอจนผิดสังเกตุ ผมเชื่อเหลือเกินว่าจะต้องเกี่ยวโยงกับการทำเอฟทีเอกับสหรัฐฯแน่นอน  " นายสุรวิชกล่าว   \nนายบัณฑูร เศรษฐศิโรตม์ อนุกรรมการในกรรมการสิทธิมนุษยชนแห่งชาติ กล่าวว่า นโยบายจีเอ็มโอของไทยตั้งอยู่บนพื้นฐานข้อมูลที่คาดเคลื่อน ขัดแย้งกับนโยบายฟู๊ดเซฟตี้ ( food safety) และเกษตรอินทรีย์อย่างสิ้นเชิง จึงอยากเรียกร้องให้รัฐบาลทบทวนมติดังกล่าว มิเช่นนั้นสหรัฐฯอาจใช้กฎหมายที่ว่าด้วยการทำเอฟทีเอกับทุกประเทศเอาเปรียบไทยได้ และไม่เห็นด้วยที่จะให้มีการทดลองภาคสนาม เพราะสามารถทดลองในห้องแล็ปได้   \nนายวิวัฒน์ ศัลยกำธร ประธานมูลนิธิกสิกรรมธรรมชาติ กล่าวว่า เชื่อว่าจะต้องมีอะไรอยู่เบื้องหลังนโยบายนี้ มิเช่นนั้นคงไม่รีบทำ จนลืมคิดไปว่าสวนทางกับนโยบายเกษตรอินทรีย์ จึงอยากเรียกร้องให้ทบทวน ไม่อยากให้ยืมจมูกคนอื่นหายใจ   \nนายวิฑูรย์ ปัญญากุล ตัวแทนจากกรีนเนท กล่าวว่า รัฐบานต้องแยกแยะพื้นที่ในการปลูกพืชจีเอ็มโอให้ชัดเจน ที่ผ่านมาไทยทำการศึกษาการปนเปื้อนทั้งในระดับเมล็ดพันธุ์ ระดับไร่นา และระดับแปรรูปน้อยมาก ดังนั้นจึงมีความจำเป็นต้องมีระบบขึ้นทะเบียนตรวจสอบ นอกจากนี้ไม่ควรให้ทางไบโอเทคเป็นผู้ดูแลกำกับการปลูก เพราะเป็นหน่วยงานที่ไม่น่าเชื่อถือ    \nนายเดชา ศิริภัทร เลขานุการมูลนิธิเกษตรกรรมยั่งยืน (ประเทศไทย) กล่าวว่า รัฐบาลประกาศสนับสนุนนโยบายเกษตรอินทรีย์ เกษตรยั่งยืน เกษตรผสมผสาน เมื่อปี 2544 แต่ขณะนี้เกษตรกรยังไม่ได้รับเงินแม้แต่บาทเดียว แต่กลับมาให้ความสำคัญกับนโยบายจีเอ็มโอที่ไม่เคยประกาศในสภาฯ   \n " ผมเห็นท่านนายกฯผลักดันเรื่องจีเอ็มโออย่างไม่มีเหตุผล เร่งรีบทำทั้งๆ ที่ไม่ใช่นโยบายที่ประกาศในสภาฯ ซึ่งถ้าท่านยังไม่หยุดความคิดเรื่องนี้ กลุ่มเกษตรกรทางเลือกทุกกลุ่มก็พร้อมจะไม่ลงคะแนนเสียงให้พรรคของท่านในการเลือกตั้งที่จะมีถึงแน่นอน"  นายเดชากล่าว    \n  รายงานโดย : สมสุข  มณีทิพย์สกุล\nศูนย์ข่าวประชาไท \n'
 ' นโยบายที่อนุญาตให้ปลูกร่วมกับพืชอื่นได้นั้นถือเป็นการชักศึกเข้าบ้าน เพราะพันธุ์พืชจีเอ็มโอมีระบบสิทธิบัตร  ระบบคุ้มครองนักปรับปรุงพันธุ์  รวมทั้งระบบความลับทางการค้า  คุ้มครองอยู่..  \nกรุงเทพฯ-23 ส.ค.47 นายเจริญ คัมภีรภาพ  อาจารย์ประจำคณะนิติศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย กล่าวว่า นโยบายที่อนุญาตให้ปลูกร่วมกับพืชอื่นได้นั้นถือเป็นการชักศึกเข้าบ้าน เพราะพันธุ์พืชจีเอ็มโอมีระบบสิทธิบัตร  ระบบคุ้มครองนักปรับปรุงพันธุ์  รวมทั้งระบบความลับทางการค้า  คุ้มครองอยู่  ซึ่งจะทำให้เกษตรกรต้องซื้อเมล็ดพันธุ์ในราคาสูงขึ้น และไม่มีหลักประกันว่าจะไม่ปนเปื้อนในธรรมชาติ  ซึ่งจะนำไปสู่การฟ้องร้องเรียกค่าเสียหายหากเกษตรกรนำพันธุ์พืชที่ปนเปื้อนนั้นไปปลูกไม่ว่าจะรู้หรือไม่ ดังที่เกิดขึ้นแล้วในประเทศแคนาดา  เพราะทรัพย์สินทางปัญญาไม่ใช่ของสาธารณะ จะใช้เมล็ดพันธุ์ของเขาซึ่งเป็นผลมาจากความรู้ของเขาก็ต้องจ่ายเงิน   \nอาจารย์จากคณะนิติศาสตร์ จุฬาฯ กล่าวด้วยว่า ผลประโยชน์ในเรื่องจีเอ็มโอนั้นใหญ่มาก  เพราะไม่ได้ขายเมล็ดพันธุ์อย่างเดียว  แต่มีทั้งปุ๋ยและสารเคมีสำหรับพืชจีเอ็มโอที่จะได้ขายควบคู่กันไปด้วย  จึงมีความพยายามผลักดันให้ไทยค่อยๆ เปิดเสรีในเรื่องนี้   \n "เชื่อได้ว่าในการทำเอฟทีเอกับอเมริกา  เราจะถูกบีบให้แก้กฎหมายลิขสิทธิ์ให้ตรงกับความต้องการของเขา  เพราะผลประโยชน์นั้นมหาศาล  อย่ามองว่าเราเป็นเพียงประเทศเล็กๆ  ในเมื่อเราสามารถส่งออกข้าวได้เกือบครึ่งโลก  ขอเพียงไทยเป็นฐานการผลิตและส่งออกข้าวจีเอ็มโอได้เท่านั้น"  นายเจริญกล่าว   \n  รายงานโดย : ศูนย์ข่าวประชาไท  \n'
 ...
 'จากกรณีที่ราชกิจจานุเบกษาได้เผยแพร่ประกาศของคณะกรรมการป้องกันและปราบปรามการทุจริตแห่งชาติ(ป.ป.ช.) เรื่อง กำหนดตำแหน่งของผู้มีหน้าที่ยื่นบัญชีทรัพย์สินและหนี้สินตามมาตรา 102 ไปเมื่อวันที่ 1 พฤศจิกายน 2561 ซึ่งจะมีผลบังคับใช้ในวันที่ 2 ธันวาคม 2561นี้ โดยกำหนดให้นายกสภามหาวิทยาลัย กรรมการสภาและอธิการบดี ของมหาวิทยาลัยในกำกับของรัฐ มหาวิทยาลัยสงฆ์ มหาวิทยาลัยของรัฐ มหาวิทยาลัยราชภัฏ และมหาวิทยาลัยเทคโนโลยีราชมงคล ยื่นบัญชีทรัพย์สินและหนี้สินของตน คู่สมรส และบุตรที่ยังไม่บรรลุนิติภาวะ รวมทั้งตรวจสอบและเปิดเผยผลการตรวจสอบทรัพย์สินและหนี้สินของบุคคลดังกล่าว ตามพระราชบัญญัติประกอบรัฐธรรมนูญว่าด้วยการป้องกันและปราบปรามการทุจริตฯ\nจากประกาศดังกล่าวได้เกิดปฏิกิริยาจากผู้ที่เป็นนายกฯและกรรมการสภาฯ ว่าเป็นการสร้างเงื่อนไขที่จุกจิกกวนใจและอำนาจหน้าที่กรรมการสภาฯไม่ได้มีอะไรมากมาย มีแต่เพียงเบี้ยประชุมครั้งละ 3,000 บาทเท่านั้น และหลายคนก็แสดงความจำนงที่จะลาออกเพื่อไม่ต้องจัดทำรายการทรัพย์สินฯโดยอ้างว่าเป็นภาระเกินสมควร และได้มีความพยายามที่จะแก้ไขปัญหาดังกล่าวด้วยการเสนอให้มีการยกเว้นหรือยกเลิกด้วยวิธีการต่างๆ แม้กระทั่งมีบางคนเสนอความเห็นให้ใช้มาตรา 44 ไปเลยก็มี จนทำให้มีการวิพากษ์วิจารณ์และถกเถียงกันอย่างกว้างขวาง ซึ่งมีทั้งเห็นด้วยและไม่เห็นด้วยกับการกระทำเช่นนี้\nฝ่ายที่สนับสนุนให้มีการยื่นบัญชีทรัพย์สินนี้ก็บอกว่าในเมื่อเป็นเจ้าหน้าที่ของรัฐระดับสูงแล้วก็ต้องยื่นบัญชีทรัพย์สินทั้งนั้นน่าจะรวมถึงคณบดีหรือวิทยาลัยป้องกันราชอาณาจักร์(วปอ.)ด้วยซ้ำไป ส่วนหนึ่งจึงมีการรณรงค์ใน change.org โดย Suthee Rattanamongkolgul ซึ่งให้เหตุผลว่าปัจจุบัน มหาวิทยาลัยหลายแห่ง เปลี่ยนแปลงสถานภาพไปเป็นมหาวิทยาลัยในกำกับของรัฐ เพื่อให้มีอิสระในการบริหารกิจการภายในได้เองทุกเรื่อง โดยมีสภามหาวิทยาลัย ที่ประกอบด้วยผู้ทรงคุณวุฒิจากบุคคลภายนอกที่มาจากการสรรหา (ของผู้บริหาร) มาทำหน้าที่กำกับดูแลนโยบายของมหาวิทยาลัย สามารถออกและ/หรือแก้ไขระเบียบข้อบังคับต่างๆ ได้\nดังนั้นการออกนอกระบบ แท้จริงแล้วคือการช่วยให้มหาวิทยาลัยมีอิสระในการดำเนินงานมากกว่าในอดีต ผู้บริหารมีอิสระและอำนาจในการทำงานมากขึ้น กรรมการสภาฯ ก็มีอำนาจมากขึ้นด้วยเช่นกัน ส่วน สกอ.และกระทรวงศึกษาธิการ แทบจะไม่มีอำนาจเข้าไปตรวจสอบใดๆ ได้อีกแล้ว เพราะอำนาจในการกำกับดูแล การตรวจสอบ ลงโทษต่างๆ อยู่ที่สภามหาวิทยาลัยโดยตรง\nที่พบเจอคือ วันนี้ผู้บริหารกับกรรมการสภาฯ เป็นพวกเดียวกันทั้งหมด ทุกอย่างดูราบรื่น ที่มาของกรรมการสภาฯ ตามระเบียบทฤษฎี ก็จะมาจากการสรรหาจากบุคลากรทั้งมหาวิทยาลัยเสนอขึ้นมา แต่ ในทางปฏิบัติ ทั้งหมดก็มาจากการคัดสรรจากผู้บริหารระดับสูงของมหาวิทยาลัยนั่นเอง โดยอาจมีผู้ทรงคุณวุฒิอาวุโสบางคนร่วมอยู่เป็นที่ปรึกษา เพื่อให้ได้กลุ่มเครือข่ายเดียวกัน\nมีข้อร้องเรียนจากอาจารย์ในบางสถาบันว่า ถ้ามีเรื่องร้องเรียนที่เกี่ยวกับกรณีที่ส่อว่าจะมีการทุจริต ประพฤติมิชอบ ของผู้บริหารระดับใดก็ตาม (ถ้าเป็นพวกเดียวกัน) ก็จะได้รับการช่วยเหลือกัน จะไม่พบการทุจริตจากการกระทำของผู้บริหารทั้งสิ้น อาจมีบ้างก็จะเป็นระดับเจ้าหน้าที่ พนักงาน บุคลากรทั่วไปเท่านั้น ดังนั้นการบริหารเงินงบประมาณ ปีละสอง สามพันล้านบาทโดยอิสระเสรีแบบนี้จึงเป็นเรื่องที่น่าเป็นห่วง เพราะในระบบบริหารงานในปัจจุบันไม่มีกลไกการคานอำนาจระหว่างกันอย่างแท้จริง\nผู้ทรงคุณวุฒิเองก็มีข้อจำกัดที่จะเข้ามาเรียกหาข้อมูลเพราะไม่มีระบบผู้ช่วย ถ้าผู้บริหารระดับสูงของมหาวิทยาลัยปิดบังข้อมูล ผู้ทรงคุณวุฒิก็จะไม่สามารถรู้ได้เลย ดังนั้นในความเป็นจริงคือ ทุกคนจึงมาประชุม อภิปรายแสดงความคิดเห็นกันเฉพาะในระหว่างการประชุมเท่านั้น จึงเป็นจุดอ่อนที่เป็นช่องทางที่จะทำให้เกิดการทุจริตขึ้นได้ง่ายเพราะไม่มีระบบตรวจสอบและไม่มีกลไกการคานอำนาจกัน\nเป็นเรื่องน่าประหลาดใจที่แม้ว่ามหาวิทยาลัยจะออกนอกระบบไปแล้ว แต่รัฐบาล (สำนักงบฯ) ก็ยังจัดสรร งบประมาณมาให้เหมือนเดิม โดยเฉพาะงบก่อสร้างและครุภัณฑ์ ไม่ได้ลดลง งบเงินเดือนพนักงานก็ยังให้ตามปกติ พนักงานมหาวิทยาลัยที่ใช้งบเงินรายได้ของคณะหรือส่วนกลางมาก่อน ก็จะได้รับการบรรจุให้เป็นพนักงาน(ประจำ) ใช้งบประมาณแผ่นดินซึ่งจะมีความมั่นคงสูงกว่า แน่นอนว่ากลุ่มที่ได้รับการบรรจุก็คือกลุ่มคนที่เป็นพวกเดียวกันหรือสนับสนุนผู้บริหารเท่านั้น ในอนาคตถ้าจะมีการปลดพนักงานออก ก็จะเป็นพนักงานกลุ่มที่ไม่ได้รับการบรรจุเป็นพนักงานเงินงบประมาณแผ่นดินนั่นเอง\nดังนั้น ในวันนี้ผู้บริหารมหาวิทยาลัย จึงได้ควบคุมอำนาจบริหารจัดการได้อย่างเบ็ดเสร็จในทุกระดับ โดยอยู่ในมือของกลุ่มผู้บริหารระดับสูงกับผู้ทรงคุณวุฒิบางคนที่เป็นหัวเรือใหญ่เครือข่ายเดียวกันเท่านั้น ด้วยสภาพการณ์แบบนี้ จึงมีโอกาสจะเกิดการทุจริตทางนโยบายขึ้นได้ ส่วนในระดับหน่วยงานตามคณะ สาขาวิชาต่างๆ ผู้บริหารส่วนนี้ก็สามารถจะกระทำทุจริตคอรัปชัน เช่น ในการจัดซื้อจัดจ้าง และงานก่อสร้างต่างๆ ได้ง่ายมาก เพราะบุคลากรผู้ปฏิบัติงานในหน่วยงานล้วนเป็นพวกเดียวกันทั้งหมดนั่นเอง ถ้ามีการร้องเรียนขึ้นไป เรื่องก็เงียบ คนร้องเรียนจะอยู่ไม่ได้\nปัจจุบันมหาวิทยาลัยจึงเป็นแหล่งผลประโยชน์ขนาดใหญ่ ที่สามารถจะทุจริตคอรัปชันได้อย่างง่ายดาย เป็นแหล่งผลประโยชน์แหล่งใหญ่ที่สังคมภายนอกมองข้ามไป เพราะอาจจะเห็นว่าเป็นสถาบันการศึกษาระดับสูง เข้าทำนองคนมีการศึกษาจะไม่โกง ที่สำคัญไม่มีใครสามารถเข้าไปตรวจสอบได้เลย\nขอยกตัวอย่างวิธีหาผลประโยชน์ของผู้บริหารและกรรมการสภาฯ เช่น ร่วมกันออกนโยบายเอาทรัพย์สิน รายได้ของมหาวิทยาลัยไปซื้อหุ้นของสถาบันการเงินที่ผู้ทรงฯ เป็นกรรมการ เปิดสัมปทานภายใน เช่น เดินรถให้เอกชนที่มีผู้ทรงฯ บางคนเป็นหุ้นส่วน สร้างโครงการก่อสร้างอาคารต่างๆ ขึ้นมามากมายจนไม่รู้จะเอาไปใช้ประโยชน์อะไร แจกโควตาที่นั่งเด็กนักเรียนสาธิต ให้ผู้ทรงฯ ทุกปี ใครช่วยเหลือเกื้อกูลกันมากก็ให้มาก ล็อกสเป็กซื้อของพรรคพวกตน ขึ้นเงินเดือน ค่าตอบแทนให้พวกกันเอง กันอย่างเต็มที่ เอาเงินไปจ้างที่ปรึกษากฎหมายมืออาชีพปีละหลายล้านบาทไว้ต่อสู้คดีกับบุคลากรของมหาวิทยาลัย เป็นต้น ถ้าเงินงบประมาณไม่พอก็ขึ้นเงินค่าเล่าเรียน\nไม่มีใคร กล้าเข้าไปตรวจสอบ เก็บหลักฐาน เจ้าหน้าที่ทุกคนจะกลัวมาก เพราะอาจถูกประเมินไล่ออกได้ง่ายมาก ดังนั้น การที่ ปปช. ออกประกาศให้ ผู้บริหารมหาวิทยาลัย และกรรมการสภาฯทุกคนยื่นบัญชีแสดงทรัพย์สิน จึงอาจพอช่วยป้องปรามการทุจริตคอรัปชันได้อีกทางหนึ่ง\nจากเหตุผลดังกล่าวข้างต้นผมเห็นว่าควรที่จะยังคงประกาศฯนี้ไว้ ใครจะลาออกก็ลาออกไป คนที่เขาอยากทำงานมีเยอะแยะ ที่สำคัญก็คือจะได้หยุดวงจรการผลัดกันเกาหลังกันเองเสียทีน่ะครับ\nเผยแพร่ครั้งแรกใน: กรุงเทพธุรกิจฉบับประจำวันพุธที่ 14 พฤศจิกายน 2561\n'

missing value

In [84]:
df.isna().sum()

url          0
date         0
title        0
body_text    0
labels       0
dtype: int64

pivot the label

In [85]:
benchmark_labels = ['การเมือง','สิทธิมนุษยชน','คุณภาพชีวิต','ต่างประเทศ','สังคม',
                  'สิ่งแวดล้อม','เศรษฐกิจ','วัฒนธรรม','แรงงาน','ความมั่นคง','ไอซีที','การศึกษา']

In [86]:
def expand_list_to_columns(row):
    classes = {c: int(c in row['labels']) for c in benchmark_labels}
    return pd.Series(classes)

In [87]:
new_cols = df.apply(expand_list_to_columns, axis=1)
df = pd.concat([df, new_cols], axis=1)

In [88]:
column_mapping = {
    "การเมือง": "politics",
    "สิทธิมนุษยชน": "human_rights",
    "คุณภาพชีวิต": "quality_of_life",
    "ต่างประเทศ": "foreign_affairs",
    "สังคม": "society",
    "สิ่งแวดล้อม": "environment",
    "เศรษฐกิจ": "economy",
    "วัฒนธรรม": "culture",
    "แรงงาน": "labor",
    "ความมั่นคง": "security",
    "ไอซีที": "ict",
    "การศึกษา": "education"
}

In [89]:
df = df.rename(columns=column_mapping)

In [90]:
df = df[['body_text','politics','human_rights','quality_of_life','foreign_affairs','society','environment','economy','culture','labor','security','ict','education']]

clean data

In [91]:
df.sample(10)

,body_text,politics,human_rights,quality_of_life,foreign_affairs,society,environment,economy,culture,labor,security,ict,education
66298,มติ สปสช. วางเป้าช่วยเหลือผู้ที่ตาบอด หรือมองเ...,0,0,1,0,0,0,0,0,0,0,0,0
39776,\n(4 มิ.ย.56) ที่ห้องประชุม 202 อาคารจามจุรี 4...,0,0,1,0,0,0,0,0,0,0,1,0
55269,22 เม.ย. 2559 จากกรณีที่วานนี้ (21 เม.ย.59) พล...,1,0,0,0,0,0,0,0,0,0,0,0
41092,บก. Wartani เปิดใจไม่กล้านอนบ้านหลังเหตุชายฉกร...,0,1,1,0,0,0,0,0,0,1,0,0
14118,\nขณะที่ค่ายเพลงยักษ์ใหญ่บางค่ายยังคงแสดงอาการ...,1,0,0,0,0,0,0,0,0,0,0,0
24570,อัดเละตีความเหมืองแร่ไม่เข้าข่ายโครงการพัฒนารุ...,0,1,1,0,0,1,0,0,0,0,0,0
9483,\nประชาไท - 22 ก.ย. 49 เมื่อวันที่ 21 ก.ย. นาย...,1,0,0,0,0,0,0,0,0,0,0,0
10567,\nทีมข่าวประชาไทภาคเหนือ : รายงาน\n\n \n\n\n\n...,0,0,0,0,0,0,0,0,0,0,0,0
15786,\nการเมือง\n\n \n\n \n\nสุรพงษ์หนุนแก้รธน. ฟื้...,1,0,0,0,0,0,0,0,0,0,0,0
8647,\nประชาไท8 ก.ค. 2549 นายสุริยะใส กตะศิลา ผู้ป...,1,0,0,0,0,0,0,0,0,0,0,0

In [105]:
import re
from pythainlp.util import normalize
from pythainlp import thai_characters
from pythainlp.corpus import thai_stopwords
from pythainlp.tokenize import word_tokenize

In [93]:
def normalize_text(text):
    return normalize(text)

In [94]:
def remove_html_tags(text):
    return re.sub(r'<[^>]+>', '', text)

In [95]:
def remove_urls(text):
    URL_PATTERN = r"""(?i)\b((?:https?:(?:/{1,3}|[a-z0-9%])|[a-z0-9.\-]+[.](?:com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|name|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|Ja|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)/)(?:[^\s()<>{}\[\]]+|\([^\s()]*?\([^\s()]+\)[^\s()]*?\)|\([^\s]+?\))+(?:\([^\s()]*?\([^\s()]+\)[^\s()]*?\)|\([^\s]+?\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’])|(?:(?<!@)[a-z0-9]+(?:[.\-][a-z0-9]+)*[.](?:com|net|org|edu|gov|mil|aero|asia|biz|cat|coop|info|int|jobs|mobi|museum|name|post|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|Ja|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)\b/?(?!@)))"""
    return re.sub(URL_PATTERN, '', text)

In [96]:
def remove_thai_months(text):
    thai_months_full = ["มกราคม", "กุมภาพันธ์", "มีนาคม", "เมษายน", "พฤษภาคม", "มิถุนายน",
                        "กรกฎาคม", "สิงหาคม", "กันยายน", "ตุลาคม", "พฤศจิกายน", "ธันวาคม"]
    thai_months_abbr = ["ม.ค.", "ก.พ.", "มี.ค.", "เม.ย.", "พ.ค.", "มิ.ย.",
                        "ก.ค.", "ส.ค.", "ก.ย.", "ต.ค.", "พ.ย.", "ธ.ค."]
    for month in thai_months_full + thai_months_abbr:
        text = text.replace(month, "")
    return text

In [97]:
def remove_non_thai_characters(text):
    allowed_characters = thai_characters + "ฯ"
    escaped_allowed_characters = re.escape(allowed_characters)
    pattern = '[^' + escaped_allowed_characters + ']'
    return re.sub(pattern, '', text)

In [98]:
def remove_stopwords(text):
    stopwords = thai_stopwords()
    text_tokens = text.split()
    text_tokens = [word for word in text_tokens if word not in stopwords]
    return ''.join(text_tokens)

In [100]:
def remove_special_characters(text):
    pattern = r'[!@#$%^&*()\-+=\[\]{};:\'",<.>/?\\|]\n'
    # Replace these special characters with an empty string.
    cleaned_text = re.sub(pattern, '', text)
    
    return cleaned_text

In [99]:
def remove_words_from_text(text):
    words_to_remove = ['ประชาไท']
    for word in words_to_remove:
        text = text.replace(word, '')
    return text

In [101]:
def remove_extra_spaces(text):
    return re.sub(r'\s+', '', text).strip()

In [102]:
df['body_text'] = df['body_text'].apply(normalize_text)
df['body_text'] = df['body_text'].apply(remove_html_tags)
df['body_text'] = df['body_text'].apply(remove_urls)
df['body_text'] = df['body_text'].apply(remove_thai_months)
df['body_text'] = df['body_text'].apply(remove_non_thai_characters)
df['body_text'] = df['body_text'].apply(remove_stopwords)
df['body_text'] = df['body_text'].apply(remove_special_characters)
df['body_text'] = df['body_text'].apply(remove_words_from_text)
df['body_text'] = df['body_text'].apply(remove_extra_spaces)

In [104]:
df.sample(20)

,body_text,politics,human_rights,quality_of_life,foreign_affairs,society,environment,economy,culture,labor,security,ict,education
57923,ภาพโดยเมื่อวันที่ที่ผ่านมาในการประชุมอนุสัญญาว...,0,0,0,1,0,1,0,0,0,0,0,0
26952,ที่ใดมีการกดขี่ที่นั่นย่อมมีการต่อต้านเป็นทฤษฎ...,1,0,0,0,0,0,0,0,0,0,0,0
26143,คณะทำงานยุติธรรมเพื่อสันติภาพออกแถลงการณ์ขอให้...,1,0,0,0,0,0,0,0,0,0,0,0
244,ศูนย์ข่าวภาคใต้สำนักงานตำรวจแห่งชาติสตชเปิดศูน...,0,0,0,0,0,1,0,0,0,0,0,0
214,เชียงใหม่ผศพาวินมะโนชัยรองคณบดีฝ่ายวิจัยและบริ...,0,0,0,0,0,1,0,0,0,0,0,0
4848,ชาวสะเมิงร่วมค้านโครงการก่อสร้างเขื่อนแม่ขานศู...,1,0,0,0,0,0,0,0,0,0,0,0
55067,ในยุครัฐบาลคสชการแสดงออกทางการเมืองถูกจำกัดมาก...,1,1,0,0,0,0,0,0,0,0,0,0
32752,ผู้นำเกาหลีเหนือให้ก่อสร้างส่วนจัดแสดงโลมาในเก...,0,0,1,1,0,0,0,0,0,0,0,0
2904,ปัตตานีเมื่อเวลานพตอประเสริฐจันทร์สว่างรองผู้บ...,0,0,0,0,0,1,0,0,0,0,0,0
32753,เป็นที่ถกเถียงกันว่าผู้ใช้โซเชียลเน็ตเวิร์กควร...,0,0,0,0,1,0,0,0,0,0,1,0
50664,เวลาประมาณนที่ห้องพิจารณาคดีศาลอาญารัชดาฯมีการ...,1,1,0,0,0,0,0,0,0,0,0,0
7253,พระราชกฤษฎีกายุบสภาผู้แทนราษฎรพศให้ไว้ณวันที่พ...,1,0,0,0,0,0,0,0,0,0,0,0
36279,สภาพการณ์ของสถาบันกษัตริย์ในช่วงปลายรัชกาลคงหล...,1,0,0,0,0,0,0,0,0,0,0,0
57531,ในขณะที่ความคิดทางการเมืองกระแสหลักในสังคมไทยก...,0,1,0,0,1,0,0,1,0,0,0,0
53403,นำร่องจัดตั้งเครือข่ายชุมชนสันติธรรมในชุมชนพุท...,0,1,0,0,0,0,0,1,0,0,0,0
19131,ที่พรรคประชาธิปัตย์นายอภิสิทธิ์เวชชาชีวะนายกรั...,1,0,0,0,0,0,0,0,0,0,0,0
10751,เมื่อวันพุธที่สถานีตำรวจบางเขนกรุงเทพได้ออกหนั...,1,0,0,0,0,0,0,0,0,0,0,0
59443,กุหลาบสายประดิษฐ์เคยกล่าวไว้ว่าผู้ใดต้องการอำน...,1,0,0,0,1,0,0,0,0,0,0,0
35087,โดยการเยี่ยมชุมชนแรงงานข้ามชาติเป็นภารกิจแรกใน...,0,1,1,1,0,0,0,0,1,0,0,0
61562,ชวนเกษตรกรอ่านกลอนสู่ขวัญถ้อยคำทั่นผู้นำลึกล้ำ...,1,0,0,0,0,0,0,1,0,0,0,0

In [103]:
****

SyntaxError: invalid syntax (749935734.py, line 1)

In [106]:
def tokenize_text(text):
    return word_tokenize(text, engine='newmm')

In [107]:
df['body_text_tokenized'] = df['body_text'].apply(lambda x: tokenize_text(x))

KeyboardInterrupt:

In [ ]:
df.sample(20)

# 3. Exploratory data analysis (EDA)

In [ ]:
target_col = ['obscene','insult','toxic','severe_toxic','identity_hate','threat']

In [ ]:
df[target_col].describe()

In [ ]:
for column in target_col:
    category_counts = df[column].value_counts()
    total_count = len(df[column])
    plt.figure(figsize=(6, 8))
    ax = category_counts.plot(kind='bar')
    for i, count in enumerate(category_counts):
        percentage = (count / total_count) * 100
        ax.annotate(f'{count} ({percentage:.2f}%)', xy=(i, count), ha='center', va='bottom')
    
    plt.xlabel(column)
    plt.ylabel('Count')
    plt.title(f'Count of {column}')
    plt.show()

In [ ]:
# All the class facing with imbalance problem.

In [ ]:
df['length'] = df['comment_text'].apply(lambda x: len(str(x)))

In [ ]:
plt.figure()
plt.hist(df['length'])
plt.show()

In [ ]:
# Some messages are over than 5000 words.

In [ ]:
target_corr = df[target_col].corr()

In [ ]:
fig, ax = plt.subplots(figsize=(20, 5))
sns.heatmap(target_corr, annot=True, ax=ax)

In [ ]:
# Some of the labels are higher correlation such as obscene-insult/obscene-toxic/toxic-insult
# Classifier Chains would be good ?

# 4. Feature engineering

clean data

In [ ]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"what's", "what is ", text)
    text = re.sub(r"\'s", " ", text)
    text = re.sub(r"\'ve", " have ", text)
    text = re.sub(r"can't", "cannot ", text)
    text = re.sub(r"n't", " not ", text)
    text = re.sub(r"i'm", "i am ", text)
    text = re.sub(r"\'re", " are ", text)
    text = re.sub(r"\'d", " would ", text)
    text = re.sub(r"\'ll", " will ", text)
    text = re.sub(r"\'scuse", " excuse ", text)
    text = re.sub('\W', ' ', text)
    text = re.sub('\s+', ' ', text)
    text = text.strip(' ')
    return text

In [ ]:
df['comment_text'] = df['comment_text'].map(lambda com : clean_text(com))

In [ ]:
df.sample(10)

# 5. Model

Train/Test Split

In [ ]:
from sklearn.model_selection import train_test_split

# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(df[['comment_text']], df[['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']]
                                                    ,test_size=0.2
                                                    ,random_state=42)

In [ ]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

Vectorization/TD-IDF

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(ngram_range=(1,1))

In [ ]:
X_train_vect = vectorizer.fit_transform(X_train)
X_test_vect = vectorizer.transform(X_test)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf= TfidfVectorizer()

In [ ]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [ ]:
***

In [ ]:
def add_feature(X, feature_to_add):
    '''
    Returns sparse feature matrix with added feature.
    feature_to_add can also be a list of features.
    '''
    from scipy.sparse import csr_matrix, hstack
    return hstack([X, csr_matrix(feature_to_add).T], 'csr')

Model (Vectorization)

In [ ]:
# import and instantiate the Logistic Regression model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
logreg = LogisticRegression(C=12.0)

In [ ]:
for label in target_col:
    print('... Processing {}'.format(label))
    y = y_test[label]
    # train the model using X_dtm & y
    logreg.fit(X_train_tfidf, y)
    # compute the training accuracy
    y_pred_X = logreg.predict(X_test_tfidf)
    print('Training accuracy is {}'.format(accuracy_score(y, y_pred_X)))

In [ ]:
y

In [ ]:
X_train_tfidf